# Class union definition
setClassUnion(name = "character_or_numeric", members = c("character", "numeric"))
setClassUnion(name = "integer_or_list", members = c("integer", "list"))
setClassUnion(name = "numeric_or_list", members = c("numeric", "list"))

# Definition of generic functions
setGeneric(name = "GetId", def = function(object) {standardGeneric("GetId")})
setGeneric(name = "SetId<-", def = function(object, value) {standardGeneric("SetId<-")})
setGeneric(name = "GetDescrip", def = function(object, ...) {standardGeneric("GetDescrip")})
setGeneric(name = "SetDescrip<-", def = function(object, value) {standardGeneric("SetDescrip<-")})
setGeneric(name = "SaveAsRda", def = function(object, ...) {standardGeneric("SaveAsRda")})
setGeneric(name = "GetPlanId", def = function(object, ...) {standardGeneric("GetPlanId")})
setGeneric(name = "SetPlanId<-", def = function(object, value) {standardGeneric("SetPlanId<-")})
setGeneric(name = "GetAccBal", def = function(object, ...) {standardGeneric("GetAccBal")})
setGeneric(name = "GetAnuBen", def = function(object, ...) {standardGeneric("GetAnuBen")})
setGeneric(name = "GetAnuMatAge", def = function(object, ...) {standardGeneric("GetAnuMatAge")})
setGeneric(name = "GetFaceAmt", def = function(object, ...) {standardGeneric("GetFaceAmt")})
setGeneric(name = "GetIssAge", def = function(object, ...) {standardGeneric("GetIssAge")})
setGeneric(name = "GetIssAge2", def = function(object, ...) {standardGeneric("GetIssAge2")})
setGeneric(name = "GetIssDate", def = function(object, ...) {standardGeneric("GetIssDate")})
setGeneric(name = "GetLifeStatus", def = function(object, ...) {standardGeneric("GetLifeStatus")})
setGeneric(name = "GetLifeStatus2", def = function(object, ...) {standardGeneric("GetLifeStatus2")})
setGeneric(name = "GetModPrem", def = function(object, ...) {standardGeneric("GetModPrem")})
setGeneric(name = "GetPlan", def = function(object, ...) {standardGeneric("GetPlan")})
setGeneric(name = "GetPremMode", def = function(object, ...) {standardGeneric("GetPremMode")})
setGeneric(name = "GetPUAAmt", def = function(object, ...) {standardGeneric("GetPUAAmt")})
setGeneric(name = "GetReinProp", def = function(object, ...) {standardGeneric("GetReinProp")})
setGeneric(name = "GetRiskClass", def = function(object, ...) {standardGeneric("GetRiskClass")})
setGeneric(name = "GetRiskClass2", def = function(object, ...) {standardGeneric("GetRiskClass2")})
setGeneric(name = "HasLife2", def = function(object, ...) {standardGeneric("HasLife2")})
setGeneric(name = "GetLife2Cov", def = function(object, ...) {standardGeneric("GetLife2Cov")})
setGeneric(name = "GetExpiryDate", def = function(object, ...) {standardGeneric("GetExpiryDate")})
setGeneric(name = "GetCovMonths", def = function(object, ...) {standardGeneric("GetCovMonths")})
setGeneric(name = "GetPremMonths", def = function(object, ...) {standardGeneric("GetPremMonths")})
setGeneric(name = "GetPremTable", def = function(object, ...) {standardGeneric("GetPremTable")})
setGeneric(name = "SetPremTable<-", def = function(object, value) {standardGeneric("SetPremTable<-")})
setGeneric(name = "GetPremRate", def = function(object, ...) {standardGeneric("GetPremRate")})
setGeneric(name = "GetPremTaxRate", def = function(object, ...) {standardGeneric("GetPremTaxRate")})
setGeneric(name = "GetModFactor", def = function(object, ...) {standardGeneric("GetModFactor")})
setGeneric(name = "GetPolFee", def = function(object, ...) {standardGeneric("GetPolFee")})
setGeneric(name = "GetCommSchd", def = function(object, ...) {standardGeneric("GetCommSchd")})
setGeneric(name = "GetOvrdOnPremSchd", def = function(object, ...) {standardGeneric("GetOvrdOnPremSchd")})
setGeneric(name = "GetOvrdOnCommSchd", def = function(object, ...) {standardGeneric("GetOvrdOnCommSchd")})
setGeneric(name = "GetRein", def = function(object, ...) {standardGeneric("GetRein")})
setGeneric(name = "GetROPMat", def = function(object, ...) {standardGeneric("GetROPMat")})
setGeneric(name = "GetROPBasis", def = function(object, ...) {standardGeneric("GetROPBasis")})
setGeneric(name = "GetDthBenSchd", def = function(object, ...) {standardGeneric("GetDthBenSchd")})
setGeneric(name = "GetCVTableID", def = function(object, ...) {standardGeneric("GetCVTableID")})
setGeneric(name = "GetCVRateVector", def = function(object, ...) {standardGeneric("GetCVRateVector")})
setGeneric(name = "GetCVTable", def = function(object, ...) {standardGeneric("GetCVTable")})
setGeneric(name = "GetSurChrgSchd", def = function(object, ...) {standardGeneric("GetSurChrgSchd")})
setGeneric(name = "GetMatBenSchd", def = function(object, ...) {standardGeneric("GetMatBenSchd")})
setGeneric(name = "SetMatBenSchd<-", def = function(object, ...) {standardGeneric("SetMatBenSchd<-")})
setGeneric(name = "ProjPrem", def = function(object, ...) {standardGeneric("ProjPrem")})
setGeneric(name = "ProjComm", def = function(object, ...) {standardGeneric("ProjComm")})
setGeneric(name = "ProjDthBen", def = function(object, ...) {standardGeneric("ProjDthBen")})
setGeneric(name = "ProjMatBen", def = function(object, ...) {standardGeneric("ProjMatBen")})
setGeneric(name = "ProjCV", def = function(object, ...) {standardGeneric("ProjCV")})
setGeneric(name = "ProjSurBen", def = function(object, ...) {standardGeneric("ProjSurBen")})
setGeneric(name = "ProjRein", def = function(object, ...) {standardGeneric("ProjRein")})
setGeneric(name = "ProjAnuBen", def = function(object, ...) {standardGeneric("ProjAnuBen")})
setGeneric(name = "Project", def = function(object, ...) {standardGeneric("Project")})
setGeneric(name = "GetCovYears", def = function(object, ...) {standardGeneric("GetCovYears")})
setGeneric(name = "GetPremYears", def = function(object, ...) {standardGeneric("GetPremYears")})
setGeneric(name = "SetCovPeriod", def = function(object, ...) {standardGeneric("SetCovPeriod")})
setGeneric(name = "SetPremPeriod", def = function(object, ...) {standardGeneric("SetPremPeriod")})
setGeneric(name = "SetCommSchd<-", def = function(object, value) {standardGeneric("SetCommSchd<-")})
setGeneric(name = "SetOvrdOnCommSchd<-", def = function(object, value) {standardGeneric("SetOvrdOnCommSchd<-")})
setGeneric(name = "SetOvrdOnPremSchd<-", def = function(object, value) {standardGeneric("SetOvrdOnPremSchd<-")})
setGeneric(name = "SetModFactor<-", def = function(object, value) {standardGeneric("SetModFactor<-")})
setGeneric(name = "SetPolFee<-", def = function(object, value) {standardGeneric("SetPolFee<-")})
setGeneric(name = "SetPremTaxRate<-", def = function(object, value) {standardGeneric("SetPremTaxRate<-")})
setGeneric(name = "SetRein<-", def = function(object, value) {standardGeneric("SetRein<-")})
setGeneric(name = "SetROPMat<-", def = function(object, ...) {standardGeneric("SetROPMat<-")})
setGeneric(name = "SetROPBasis<-", def = function(object, ...) {standardGeneric("SetROPBasis<-")})
setGeneric(name = "SetCVTable<-", def = function(object, value) {standardGeneric("SetCVTable<-")})
setGeneric(name = "SetSurChrgSchd<-", def = function(object, value) {standardGeneric("SetSurChrgSchd<-")})
setGeneric(name = "SetDthBenSchd<-", def = function(object, value) {standardGeneric("SetDthBenSchd<-")})
setGeneric(name = "GetDthBenIntraYearMthd", def = function(object, value) {standardGeneric("GetDthBenIntraYearMthd")})
setGeneric(name = "SetDthBenIntraYearMthd<-", def = function(object, value) {standardGeneric("SetDthBenIntraYearMthd<-")})
setGeneric(name = "GetAssumpId", def = function(object, ...) {standardGeneric("GetAssumpId")})
setGeneric(name = "GetAssump", def = function(object, ...){standardGeneric("GetAssump")})
setGeneric(name = "GetExpdAssump", def = function(object, ...){standardGeneric("GetExpdAssump")})
setGeneric(name = "GetPaddAssump", def = function(object, ...){standardGeneric("GetPaddAssump")})
setGeneric(name = "AdjustAssump", def = function(object, ...){standardGeneric("AdjustAssump")})
setGeneric(name = "GetMortTableID", def = function(object, ...) {standardGeneric("GetMortTableID")})
setGeneric(name = "GetMortTableMult", def = function(object, ...) {standardGeneric("GetMortTableMult")})
setGeneric(name = "GetExtraMortTable", def = function(object, ...) {standardGeneric("GetExtraMortTable")})
setGeneric(name = "GetExtraMortTableMult", def = function(object, ...) {standardGeneric("GetExtraMortTableMult")})
setGeneric(name = "GetMortImprovRate", def = function(object, ...) {standardGeneric("GetMortImprovRate")})
setGeneric(name = "GetMortPfad", def = function(object, ...) {standardGeneric("GetMortPfad")})
setGeneric(name = "GetMortTable", def = function(object, ...) {standardGeneric("GetMortTable")})
setGeneric(name = "GetExtraQTable", def = function(object, ...) {standardGeneric("GetExtraQTable")})
setGeneric(name = "SetAssumpId<-", def = function(object, value) {standardGeneric("SetAssumpId<-")})
setGeneric(name = "SetMortTable<-", def = function(object, value) {standardGeneric("SetMortTable<-")})
setGeneric(name = "SetMortTableMult<-", def = function(object, value) {standardGeneric("SetMortTableMult<-")})
setGeneric(name = "SetExtraMortTable<-", def = function(object, value) {standardGeneric("SetExtraMortTable<-")})
setGeneric(name = "SetExtraMortTableMult<-", def = function(object, value) {standardGeneric("SetExtraMortTableMult<-")})
setGeneric(name = "SetMortImprovRate<-", def = function(object, value) {standardGeneric("SetMortImprovRate<-")})
setGeneric(name = "SetMortPfad<-", def = function(object, value) {standardGeneric("SetMortPfad<-")})
setGeneric(name = "GetMortAssump1", def = function(object) {standardGeneric("GetMortAssump1")})
setGeneric(name = "GetMortAssump2", def = function(object) {standardGeneric("GetMortAssump2")})
setGeneric(name = "SetMortAssump1<-", def = function(object, value) {standardGeneric("SetMortAssump1<-")})
setGeneric(name = "SetMortAssump2<-", def = function(object, value) {standardGeneric("SetMortAssump2<-")})
setGeneric(name = "GetPUA", def = function(object, ...) {standardGeneric("GetPUA")})
setGeneric(name = "SetPUA<-", def = function(object, value) {standardGeneric("SetPUA<-")})
setGeneric(name = "ProjPUA", def = function(object, ...) {standardGeneric("ProjPUA")})
setGeneric(name = "IsPUAPaidOnDth", def = function(object) {standardGeneric("IsPUAPaidOnDth")})
setGeneric(name = "IsPUAPaidOnMat", def = function(object) {standardGeneric("IsPUAPaidOnMat")})
setGeneric(name = "IsPUAPaidOnSur", def = function(object) {standardGeneric("IsPUAPaidOnSur")})
setGeneric(name = "IsPUAPaidOnDth<-", def = function(object, value) {standardGeneric("IsPUAPaidOnDth<-")})
setGeneric(name = "IsPUAPaidOnMat<-", def = function(object, value) {standardGeneric("IsPUAPaidOnMat<-")})
setGeneric(name = "IsPUAPaidOnSur<-", def = function(object, value) {standardGeneric("IsPUAPaidOnSur<-")})
setGeneric(name = "SetPUASchd<-", def = function(object, value) {standardGeneric("SetPUASchd<-")})
setGeneric(name = "SetPUACreditMonth<-", def = function(object, value) {standardGeneric("SetPUACreditMonth<-")})
setGeneric(name = "ProjPremLoad", def = function(object, ...) {standardGeneric("ProjPremLoad")})
setGeneric(name = "ProjAccBal", def = function(object, ...) {standardGeneric("ProjAccBal")})
setGeneric(name = "LookUp", def = function(tbl, lookUpKey, ...) {standardGeneric("LookUp")})
setGeneric(name = "GetSource", def = function(object) {standardGeneric("GetSource")})
setGeneric(name = "SetSource<-", def = function(object, value) {standardGeneric("SetSource<-")})
setGeneric(name = "GetCreatedBy", def = function(object) {standardGeneric("GetCreatedBy")})
setGeneric(name = "SetCreatedBy<-", def = function(object, value) {standardGeneric("SetCreatedBy<-")})
setGeneric(name = "GetCreatedAt", def = function(object) {standardGeneric("GetCreatedAt")})
setGeneric(name = "SetCreatedAt<-", def = function(object, value) {standardGeneric("SetCreatedAt<-")})
setGeneric(name = "GetTBase", def = function(object) {standardGeneric("GetTBase")})
setGeneric(name = "GetMinAge", def = function(object) {standardGeneric("GetMinAge")})
setGeneric(name = "GetMaxAge", def = function(object) {standardGeneric("GetMaxAge")})
setGeneric(name = "GetMaxPolYear", def = function(object) {standardGeneric("GetMaxPolYear")})
setGeneric(name = "GetMinBirthYear", def = function(object) {standardGeneric("GetMinBirthYear")})
setGeneric(name = "GetMaxBirthYear", def = function(object) {standardGeneric("GetMaxBirthYear")})
setGeneric(name = "GetUltTable", def = function(object) {standardGeneric("GetUltTable")})
setGeneric(name = "GetMinSelAge", def = function(object) {standardGeneric("GetMinSelAge")})
setGeneric(name = "GetMaxSelAge", def = function(object) {standardGeneric("GetMaxSelAge")})
setGeneric(name = "GetSelPeriod", def = function(object) {standardGeneric("GetSelPeriod")})
setGeneric(name = "GetMaxAttAge", def = function(object) {standardGeneric("GetMaxAttAge")})
setGeneric(name = "GetMinCalYear", def = function(object) {standardGeneric("GetMinCalYear")})
setGeneric(name = "GetMaxCalYear", def = function(object) {standardGeneric("GetMaxCalYear")})
setGeneric(name = "GetCovID", def = function(object, value) {standardGeneric("GetCovID")})
setGeneric(name = "SetCovID<-", def = function(object, value) {standardGeneric("SetCovID<-")})
setGeneric(name = "SetIssDate<-", def = function(object, value) {standardGeneric("SetIssDate<-")})
setGeneric(name = "SetIssAge<-", def = function(object, value) {standardGeneric("SetIssAge<-")})
setGeneric(name = "SetIssAge2<-", def = function(object, value) {standardGeneric("SetIssAge2<-")})
setGeneric(name = "SetRiskClass<-", def = function(object, value) {standardGeneric("SetRiskClass<-")})
setGeneric(name = "SetRiskClass2<-", def = function(object, value) {standardGeneric("SetRiskClass2<-")})
setGeneric(name = "SetFaceAmt<-", def = function(object, value) {standardGeneric("SetFaceAmt<-")})
setGeneric(name = "SetPremMode<-", def = function(object, value) {standardGeneric("SetPremMode<-")})
setGeneric(name = "SetModPrem<-", def = function(object, value) {standardGeneric("SetModPrem<-")})
setGeneric(name = "SetLifeStatus<-", def = function(object, value) {standardGeneric("SetLifeStatus<-")})
setGeneric(name = "SetLifeStatus2<-", def = function(object, value) {standardGeneric("SetLifeStatus2<-")})
setGeneric(name = "SetAnuMatAge<-", def = function(object, value) {standardGeneric("SetAnuMatAge<-")})
setGeneric(name = "SetAnuBen<-", def = function(object, value) {standardGeneric("SetAnuBen<-")})
setGeneric(name = "SetReinProp<-", def = function(object, value) {standardGeneric("SetReinProp<-")})
setGeneric(name = "SetPUAAmt<-", def = function(object, value) {standardGeneric("SetPUAAmt<-")})
setGeneric(name = "SetAccBal<-", def = function(object, value) {standardGeneric("SetAccBal<-")})
setGeneric(name = "GetBaseMortRateVector", def = function(object, cov, ...) {standardGeneric("GetBaseMortRateVector")})
setGeneric(name = "GetExtraMortRateVector", def = function(object, cov, ...) {standardGeneric("GetExtraMortRateVector")})
setGeneric(name = "GetMortImprovAdjVector", def = function(object, cov, ...) {standardGeneric("GetMortImprovAdjVector")})
setGeneric(name = "GetMargin", def = function(object, cov, ...) {standardGeneric("GetMargin")})
setGeneric(name = "Run", def = function(object, var, result, ...){standardGeneric("Run")})
setGeneric(name = "GetRunId", def = function(object) {standardGeneric("GetRunId")})
setGeneric(name = "SetRunId<-", def = function(object, value) {standardGeneric("SetRunId<-")})
setGeneric(name = "GetArgsId", def = function(object) {standardGeneric("GetArgsId")})
setGeneric(name = "SetArgsId<-", def = function(object, value) {standardGeneric("SetArgsId<-")})
setGeneric(name = "GetArgNames", def = function(object) {standardGeneric("GetArgNames")})
setGeneric(name = "Contains", def = function(object, itemName) {standardGeneric("Contains")})
setGeneric(name = "GetArgClass", def = function(object, argName) {standardGeneric("GetArgClass")})
setGeneric(name = "GetArgValue", def = function(object, argName) {standardGeneric("GetArgValue")})
setGeneric(name = "SetArgValue", def = function(object, ...) {standardGeneric("SetArgValue")})
setGeneric(name = "GetLapseRate", def = function(object, ...) {standardGeneric("GetLapseRate")})
setGeneric(name = "GetLapseRateMult", def = function(object, ...) {standardGeneric("GetLapseRateMult")})
setGeneric(name = "GetLapseRateFlatExtra", def = function(object, ...) {standardGeneric("GetLapseRateFlatExtra")})
setGeneric(name = "GetLapsePfad", def = function(object, ...) {standardGeneric("GetLapsePfad")})
setGeneric(name = "SetLapseRate<-", def = function(object, value) {standardGeneric("SetLapseRate<-")})
setGeneric(name = "SetLapseRateMult<-", def = function(object, value) {standardGeneric("SetLapseRateMult<-")})
setGeneric(name = "SetLapseRateFlatExtra<-", def = function(object, value) {standardGeneric("SetLapseRateFlatExtra<-")})
setGeneric(name = "SetLapsePfad<-", def = function(object, value) {standardGeneric("SetLapsePfad<-")})
setGeneric(name = "GetLapseRateVector", def = function(object, cov) {standardGeneric("GetLapseRateVector")})
setGeneric(name = "GetAcqExpnsPerPol", def = function(object, ...) {standardGeneric("GetAcqExpnsPerPol")})
setGeneric(name = "GetAcqExpnsPerFaceAmt", def = function(object, ...) {standardGeneric("GetAcqExpnsPerFaceAmt")})
setGeneric(name = "GetMntExpnsPerPol", def = function(object, ...) {standardGeneric("GetMntExpnsPerPol")})
setGeneric(name = "GetMntExpnsPerPrem", def = function(object, ...) {standardGeneric("GetMntExpnsPerPrem")})
setGeneric(name = "GetMntExpnsPerPremAmt", def = function(object, ...) {standardGeneric("GetMntExpnsPerPremAmt")})
setGeneric(name = "GetMntExpnsPerClaim", def = function(object, ...) {standardGeneric("GetMntExpnsPerClaim")})
setGeneric(name = "SetAcqExpnsPerPol<-", def = function(object, value) {standardGeneric("SetAcqExpnsPerPol<-")})
setGeneric(name = "SetAcqExpnsPerFaceAmt<-", def = function(object, value) {standardGeneric("SetAcqExpnsPerFaceAmt<-")})
setGeneric(name = "SetMntExpnsPerPol<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPol<-")})
setGeneric(name = "SetMntExpnsPerPrem<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPrem<-")})
setGeneric(name = "SetMntExpnsPerPremAmt<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPremAmt<-")})
setGeneric(name = "SetMntExpnsPerClaim<-", def = function(object, value) {standardGeneric("SetMntExpnsPerClaim<-")})
setGeneric(name = "GetAcqExpnsPerPolPfad", def = function(object, ...) {standardGeneric("GetAcqExpnsPerPolPfad")})
setGeneric(name = "GetAcqExpnsPerFaceAmtPfad", def = function(object, ...) {standardGeneric("GetAcqExpnsPerFaceAmtPfad")})
setGeneric(name = "GetMntExpnsPerPolPfad", def = function(object, ...) {standardGeneric("GetMntExpnsPerPolPfad")})
setGeneric(name = "GetMntExpnsPerPremPfad", def = function(object, ...) {standardGeneric("GetMntExpnsPerPremPfad")})
setGeneric(name = "GetMntExpnsPerPremAmtPfad", def = function(object, ...) {standardGeneric("GetMntExpnsPerPremAmtPfad")})
setGeneric(name = "SetAcqExpnsPerPolPfad<-", def = function(object, value) {standardGeneric("SetAcqExpnsPerPolPfad<-")})
setGeneric(name = "SetAcqExpnsPerFaceAmtPfad<-", def = function(object, value) {standardGeneric("SetAcqExpnsPerFaceAmtPfad<-")})
setGeneric(name = "SetMntExpnsPerPolPfad<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPolPfad<-")})
setGeneric(name = "SetMntExpnsPerPremPfad<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPremPfad<-")})
setGeneric(name = "SetMntExpnsPerPremAmtPfad<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPremAmtPfad<-")})
setGeneric(name = "SetMntExpnsPerClaimPfad<-", def = function(object, value) {standardGeneric("SetMntExpnsPerClaimPfad<-")})
setGeneric(name = "GetAcqExpnsPerPolInflRate", def = function(object, ...) {standardGeneric("GetAcqExpnsPerPolInflRate")})
setGeneric(name = "GetMntExpnsPerPolInflRate", def = function(object, ...) {standardGeneric("GetMntExpnsPerPolInflRate")})
setGeneric(name = "GetMntExpnsPerPremInflRate", def = function(object, ...) {standardGeneric("GetMntExpnsPerPremInflRate")})
setGeneric(name = "SetAcqExpnsPerPolInflRate<-", def = function(object, value) {standardGeneric("SetAcqExpnsPerPolInflRate<-")})
setGeneric(name = "SetMntExpnsPerPolInflRate<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPolInflRate<-")})
setGeneric(name = "SetMntExpnsPerPremInflRate<-", def = function(object, value) {standardGeneric("SetMntExpnsPerPremInflRate<-")})
setGeneric(name = "SetMntExpnsPerClaimInflRate<-", def = function(object, value) {standardGeneric("SetMntExpnsPerClaimInflRate<-")})
setGeneric(name = "GetIntrRate", def = function(object, ...) {standardGeneric("GetIntrRate")})
setGeneric(name = "GetIntrPfad", def = function(object, ...) {standardGeneric("GetIntrPfad")})
setGeneric(name = "SetIntrRate<-", def = function(object, ...) {standardGeneric("SetIntrRate<-")})
setGeneric(name = "SetIntrPfad<-", def = function(object, ...) {standardGeneric("SetIntrPfad<-")})
setGeneric(name = "GetReinId", def = function(object) {standardGeneric("GetReinId")})
setGeneric(name = "SetReinId<-", def = function(object, ...) {standardGeneric("SetReinId<-")})
setGeneric(name = "GetPremTableMult", def = function(object, ...) {standardGeneric("GetPremTableMult")})
setGeneric(name = "GetRetnProp", def = function(object, ...) {standardGeneric("GetRetnProp")})
setGeneric(name = "GetRetnLimit", def = function(object, ...) {standardGeneric("GetRetnLimit")})
setGeneric(name = "GetMinReinAmt", def = function(object, ...) {standardGeneric("GetMinReinAmt")})
setGeneric(name = "GetRfndUrndPremOnLapse", def = function(object, ...) {standardGeneric("GetRfndUrndPremOnLapse")})
setGeneric(name = "GetRfndUrndCommOnLapse", def = function(object, ...) {standardGeneric("GetRfndUrndCommOnLapse")})
setGeneric(name = "SetPremTableMult<-", def = function(object, ...) {standardGeneric("SetPremTableMult<-")})
setGeneric(name = "SetRetnProp<-", def = function(object, ...) {standardGeneric("SetRetnProp<-")})
setGeneric(name = "SetRetnLimit<-", def = function(object, ...) {standardGeneric("SetRetnLimit<-")})
setGeneric(name = "SetMinReinAmt<-", def = function(object, ...) {standardGeneric("SetMinReinAmt<-")})
setGeneric(name = "SetRfndUrndPremOnLapse<-", def = function(object, ...) {standardGeneric("SetRfndUrndPremOnLapse<-")})
setGeneric(name = "SetRfndUrndCommOnLapse<-", def = function(object, ...) {standardGeneric("SetRfndUrndCommOnLapse<-")})
setGeneric(name = "ProjNaar", def = function(object, ...) {standardGeneric("ProjNaar")})
setGeneric(name = "ProjReinNaar", def = function(object, ...) {standardGeneric("ProjReinNaar")})
setGeneric(name = "GetInpVars", def = function(object) {standardGeneric("GetInpVars")})
setGeneric(name = "SetInpVars<-", def = function(object, value) {standardGeneric("SetInpVars<-")})
setGeneric(name = "Initialize", def = function(object, ...) {standardGeneric("Initialize")})
setGeneric(name = "Finalize", def = function(object, ...) {standardGeneric("Finalize")})
setGeneric(name = "Dispatch", def = function(object, inpVar) {standardGeneric("Dispatch")})
setGeneric(name = "GetLoanIntrRate", def = function(object) {standardGeneric("GetLoanIntrRate")})
setGeneric(name = "GetLoanIntrRateType", def = function(object) {standardGeneric("GetLoanIntrRateType")})
setGeneric(name = "Deploy", def = function(object, overwrite) {standardGeneric("Deploy")})
setGeneric(name = "GetMortAssump", def = function(object) {standardGeneric("GetMortAssump")})
setGeneric(name = "GetLapseAssump", def = function(object) {standardGeneric("GetLapseAssump")})
setGeneric(name = "GetExpnsAssump", def = function(object) {standardGeneric("GetExpnsAssump")})
setGeneric(name = "GetIntrAssump", def = function(object) {standardGeneric("GetIntrAssump")})
setGeneric(name = "GetArgs", def = function(object, ...) {standardGeneric("GetArgs")})
setGeneric(name = "SetArgs<-", def = function(object, value) {standardGeneric("SetArgs<-")})
setGeneric(name = "RunParallel", def = function(object, ...) {standardGeneric("RunParallel")})
setGeneric(name = "GetAnuMode", def = function(object) {standardGeneric("GetAnuMode")})
setGeneric(name = "SetAnuMode<-", def = function(object, value) {standardGeneric("SetAnuMode<-")})
setGeneric(name = "GetAnuTiming", def = function(object) {standardGeneric("GetAnuTiming")})
setGeneric(name = "SetAnuTiming<-", def = function(object, value) {standardGeneric("SetAnuTiming<-")})
setGeneric(name = "GetAnuCrtnMonths", def = function(object) {standardGeneric("GetAnuCrtnMonths")})
setGeneric(name = "SetAnuCrtnMonths<-", def = function(object, value) {standardGeneric("SetAnuCrtnMonths<-")})
setGeneric(name = "Run.CF", def = function(object, plan, cov, ...) {standardGeneric("Run.CF")})
setGeneric(name = "GetReportClass1", def = function(object) {standardGeneric("GetReportClass1")})
setGeneric(name = "SetReportClass1<-", def = function(object, value) {standardGeneric("SetReportClass1<-")})
setGeneric(name = "GetReportClass2", def = function(object) {standardGeneric("GetReportClass2")})
setGeneric(name = "SetReportClass2<-", def = function(object, value) {standardGeneric("SetReportClass2<-")})
setGeneric(name = "GetReportClass3", def = function(object) {standardGeneric("GetReportClass3")})
setGeneric(name = "SetReportClass3<-", def = function(object, value) {standardGeneric("SetReportClass3<-")})
setGeneric(name = "GetModel", def = function(object, ...) {standardGeneric("GetModel")})
setGeneric(name = "SetModel<-", def = function(object, value) {standardGeneric("SetModel<-")})
setGeneric(name = "GetScnrList", def = function(object) {standardGeneric("GetScnrList")})
setGeneric(name = "SetScnrList<-", def = function(object, value) {standardGeneric("SetScnrList<-")})
setGeneric(name = "GetProjStartDate", def = function(object) {standardGeneric("GetProjStartDate")})
setGeneric(name = "SetProjStartDate<-", def = function(object, value) {standardGeneric("SetProjStartDate<-")})
setGeneric(name = "GetProjYears", def = function(object) {standardGeneric("GetProjYears")})
setGeneric(name = "SetProjYears<-", def = function(object, value) {standardGeneric("SetProjYears<-")})
setGeneric(name = "GetProjMonths", def = function(object) {standardGeneric("GetProjMonths")})
setGeneric(name = "IsAnnualized", def = function(object) {standardGeneric("IsAnnualized")})
setGeneric(name = "IsAnnualized<-", def = function(object, value) {standardGeneric("IsAnnualized<-")})
setGeneric(name = "ExportToExcel", def = function(object, ...) {standardGeneric("ExportToExcel")})
setGeneric(name = ".ExportToExcel.TValue", def = function(object, wb, sheet, startRow, startCol, ...) {standardGeneric(".ExportToExcel.TValue")})
setGeneric(name = "GetCovTimeline", def = function(object) {standardGeneric("GetCovTimeline")})
setGeneric(name = "GetCovProjTimeline", def = function(object) {standardGeneric("GetCovProjTimeline")})
setGeneric(name = "GetProjTimeline", def = function(object) {standardGeneric("GetProjTimeline")})
setGeneric(name = "GetCovProjTimeIndex", def = function(object) {standardGeneric("GetCovProjTimeIndex")})
setGeneric(name = "GetProjLen", def = function(object) {standardGeneric("GetProjLen")})
setGeneric(name = "GetCovProjLen", def = function(object) {standardGeneric("GetCovProjLen")})
setGeneric(name = "GetProjTimeLabel", def = function(object) {standardGeneric("GetProjTimeLabel")})
setGeneric(name = "GetCovProjTimeLabel", def = function(object) {standardGeneric("GetCovProjTimeLabel")})
setGeneric(name = "ExportToExcel<-", def = function(object, value) {standardGeneric("ExportToExcel<-")})
setGeneric(name = "ExportToRda", def = function(object, ...) {standardGeneric("ExportToRda")})
setGeneric(name = "ExportToRda<-", def = function(object, value) {standardGeneric("ExportToRda<-")})
setGeneric(name = "SetMortAssump<-", def = function(object, value) {standardGeneric("SetMortAssump<-")})
setGeneric(name = "SetLapseAssump<-", def = function(object, value) {standardGeneric("SetLapseAssump<-")})
setGeneric(name = "SetExpnsAssump<-", def = function(object, value) {standardGeneric("SetExpnsAssump<-")})
setGeneric(name = "SetIntrAssump<-", def = function(object, value) {standardGeneric("SetIntrAssump<-")})
setGeneric(name = "ApplyMortMargin", def = function(object) {standardGeneric("ApplyMortMargin")})
setGeneric(name = "ApplyLapseMargin", def = function(object) {standardGeneric("ApplyLapseMargin")})
setGeneric(name = "ApplyExpnsMargin", def = function(object) {standardGeneric("ApplyExpnsMargin")})
setGeneric(name = "ApplyIntrMargin", def = function(object) {standardGeneric("ApplyIntrMargin")})
setGeneric(name = "ApplyMortMargin<-", def = function(object, value) {standardGeneric("ApplyMortMargin<-")})
setGeneric(name = "ApplyLapseMargin<-", def = function(object, value) {standardGeneric("ApplyLapseMargin<-")})
setGeneric(name = "ApplyExpnsMargin<-", def = function(object, value) {standardGeneric("ApplyExpnsMargin<-")})
setGeneric(name = "ApplyIntrMargin<-", def = function(object, value) {standardGeneric("ApplyIntrMargin<-")})
setGeneric(name = "GetValuDate", def = function(object) {standardGeneric("GetValuDate")})
setGeneric(name = "SetValuDate<-", def = function(object, value) {standardGeneric("SetValuDate<-")})
setGeneric(name = "GetResFloor", def = function(object) {standardGeneric("GetResFloor")})
setGeneric(name = "SetResFloor<-", def = function(object, value) {standardGeneric("SetResFloor<-")})
setGeneric(name = "GetPricIssAge", def = function(object, ...) {standardGeneric("GetPricIssAge")})
setGeneric(name = "GetPricFaceAmt", def = function(object, ...) {standardGeneric("GetPricFaceAmt")})
setGeneric(name = "GetPricPremMode", def = function(object) {standardGeneric("GetPricPremMode")})
setGeneric(name = "GetUnitFaceAmt", def = function(object) {standardGeneric("GetUnitFaceAmt")})
setGeneric(name = "GetTargProfitMargin", def = function(object, ...) {standardGeneric("GetTargProfitMargin")})
setGeneric(name = "GetRndDigits", def = function(object) {standardGeneric("GetRndDigits")})
setGeneric(name = "GetOptmzInterval", def = function(object) {standardGeneric("GetOptmzInterval")})
setGeneric(name = "GetOptmzTolerance", def = function(object) {standardGeneric("GetOptmzTolerance")})
setGeneric(name = "SetPricIssAge<-", def = function(object, value) {standardGeneric("SetPricIssAge<-")})
setGeneric(name = "SetPricFaceAmt<-", def = function(object, value) {standardGeneric("SetPricFaceAmt<-")})
setGeneric(name = "SetPricPremMode<-", def = function(object, value) {standardGeneric("SetPricPremMode<-")})
setGeneric(name = "SetUnitFaceAmt<-", def = function(object, value) {standardGeneric("SetUnitFaceAmt<-")})
setGeneric(name = "SetTargProfitMargin<-", def = function(object, value) {standardGeneric("SetTargProfitMargin<-")})
setGeneric(name = "SetRndDigits<-", def = function(object, value) {standardGeneric("SetRndDigits<-")})
setGeneric(name = "SetOptmzInterval<-", def = function(object, value) {standardGeneric("SetOptmzInterval<-")})
setGeneric(name = "SetOptmzTolerance<-", def = function(object, value) {standardGeneric("SetOptmzTolerance<-")})
setGeneric(name = "GetArgsList", def = function(object) {standardGeneric("GetArgsList")})
setGeneric(name = "GetValuDates", def = function(object) {standardGeneric("GetValuDates")})
setGeneric(name = "GetCovId", def = function(object) {standardGeneric("GetCovId")})
setGeneric(name = "SetCovId<-", def = function(object, value) {standardGeneric("SetCovId<-")})
setGeneric(name = "SetPlan<-", def = function(object, value) {standardGeneric("SetPlan<-")})
setGeneric(name = "Validate", def = function(object, value) {standardGeneric("Validate")})
setGeneric(name = "ProjAcqExpns", def = function(object, ...) {standardGeneric("ProjAcqExpns")})
setGeneric(name = "ProjMntExpns", def = function(object, ...) {standardGeneric("ProjMntExpns")})
setGeneric(name = "ProjMntExpnsPerPol", def = function(object, ...) {standardGeneric("ProjMntExpnsPerPol")})
setGeneric(name = "ProjMntExpnsPerPrem", def = function(object, ...) {standardGeneric("ProjMntExpnsPerPrem")})
setGeneric(name = "ProjMntExpnsPerClaim", def = function(object, ...) {standardGeneric("ProjMntExpnsPerClaim")})
setGeneric(name = "GetArgSetId", def = function(object) {standardGeneric("GetArgSetId")})
setGeneric(name = "SetArgSetId<-", def = function(object, value) {standardGeneric("SetArgSetId<-")})
setGeneric(name = "GetModelId", def = function(object) {standardGeneric("GetModelId")})
setGeneric(name = "SetModelId<-", def = function(object, value) {standardGeneric("SetModelId<-")})
setGeneric(name = "GetJobId", def = function(object) {standardGeneric("GetJobId")})
setGeneric(name = "SetJobId<-", def = function(object, value) {standardGeneric("SetJobId<-")})
setGeneric(name = "SetDispatcher<-", def = function(object, func) {standardGeneric("SetDispatcher<-")})
setGeneric(name = "GetPUAId", def = function(object) {standardGeneric("GetPUAId")})
setGeneric(name = "SetPUAId<-", def = function(object, value) {standardGeneric("SetPUAId<-")})
setGeneric(name = "GetDthTiming", def = function(object) {standardGeneric("GetDthTiming")})
setGeneric(name = "SetDthTiming<-", def = function(object, value) {standardGeneric("SetDthTiming<-")})
setGeneric(name = "GetMessage", def = function(object) {standardGeneric("GetMessage")})
setGeneric(name = "AddMessage<-", def = function(object, value) {standardGeneric("AddMessage<-")})
setGeneric(name = "NoMessage", def = function(object) {standardGeneric("NoMessage")})
setGeneric(name = "GetPremAdj", def = function(object, ...) {standardGeneric("GetPremAdj")})
setGeneric(name = "SetPremAdj<-", def = function(object, value) {standardGeneric("SetPremAdj<-")})
setGeneric(name = "GetPremPfad", def = function(object, ...) {standardGeneric("GetPremPfad")})
setGeneric(name = "SetPremPfad<-", def = function(object, value) {standardGeneric("SetPremPfad<-")})
setGeneric(name = "SetLoanIntrRate<-", def = function(object, value) {standardGeneric("SetLoanIntrRate<-")})
setGeneric(name = "SetLoanIntrRateType<-", def = function(object, value) {standardGeneric("SetLoanIntrRateType<-")})
setGeneric(name = "GetSurvAnuBenPct", def = function(object) {standardGeneric("GetSurvAnuBenPct")})
setGeneric(name = "SetSurvAnuBenPct<-", def = function(object, value) {standardGeneric("SetSurvAnuBenPct<-")})
setGeneric(name = "TableExists", def = function(conn, tableName) {standardGeneric("TableExists")})
setGeneric(name = "CreateTable", def = function(conn, tableName, dbColSpec, ...) {standardGeneric("CreateTable")})
setGeneric(name = "CreateIndex", def = function(conn, tableName, indexCol, ...) {standardGeneric("CreateIndex")})
setGeneric(name = "DeleteTable", def = function(conn, tableName) {standardGeneric("DeleteTable")})
setGeneric(name = "WriteTable", def = function(conn, tableName, data, ...) {standardGeneric("WriteTable")})
setGeneric(name = "ReadTable", def = function(conn, tableName, ...) {standardGeneric("ReadTable")})
setGeneric(name = "CreateTable.Cov", def = function(conn) {standardGeneric("CreateTable.Cov")})
setGeneric(name = "WriteTable.Cov", def = function(conn, data, ...) {standardGeneric("WriteTable.Cov")})
setGeneric(name = "ReadTable.Cov", def = function(conn, ...) {standardGeneric("ReadTable.Cov")})
setGeneric(name = "CreateTable.ValuSumm", def = function(conn) {standardGeneric("CreateTable.ValuSumm")})
setGeneric(name = "CreateTable.Cf", def = function(conn) {standardGeneric("CreateTable.Cf")})
setGeneric(name = "CreateTable.Pfad", def = function(conn) {standardGeneric("CreateTable.Pfad")})
setGeneric(name = "WriteTable.ValuSumm", def = function(conn, data, ...) {standardGeneric("WriteTable.ValuSumm")})
setGeneric(name = "WriteTable.Cf", def = function(conn, data, ...) {standardGeneric("WriteTable.Cf")})
setGeneric(name = "WriteTable.Pfad", def = function(conn, data, ...) {standardGeneric("WriteTable.Pfad")})
setGeneric(name = "DeleteRows", def = function(conn, tableName, where) {standardGeneric("DeleteRows")})
setGeneric(name = "GetMaxProjYears", def = function(object) {standardGeneric("GetMaxProjYears")})
setGeneric(name = "SetMaxProjYears<-", def = function(object, value) {standardGeneric("SetMaxProjYears<-")})
setGeneric(name = "CompactDb", def = function(conn) {standardGeneric("CompactDb")})
setGeneric(name = "ConnectDb", def = function(object, ...) {standardGeneric("ConnectDb")})
setGeneric(name = "DisconnectDb", def = function(object) {standardGeneric("DisconnectDb")})
setGeneric(name = "GetSurChrg", def = function(object, cov, resultContainer) {standardGeneric("GetSurChrg")})
setGeneric(name = "ProjFund", def = function(object, cov, resultContainer, ...) {standardGeneric("ProjFund")})
setGeneric(name = "GetIntrCredRate", def = function(object, ...) {standardGeneric("GetIntrCredRate")})
setGeneric(name = "SetIntrCredRate<-", def = function(object, value) {standardGeneric("SetIntrCredRate<-")})
setGeneric(name = "GetPremAssump", def = function(object) {standardGeneric("GetPremAssump")})
setGeneric(name = "SetPremAssump<-", def = function(object, value) {standardGeneric("SetPremAssump<-")})
setGeneric(name = "GetIntrCredAssump", def = function(object) {standardGeneric("GetIntrCredAssump")})
setGeneric(name = "SetIntrCredAssump<-", def = function(object, value) {standardGeneric("SetIntrCredAssump<-")})
setGeneric(name = "ApplyPremMargin", def = function(object) {standardGeneric("ApplyPremMargin")})
setGeneric(name = "ApplyPremMargin<-", def = function(object, value) {standardGeneric("ApplyPremMargin<-")})
setGeneric(name = "GetPremLoadSchd", def = function(object, ...) {standardGeneric("GetPremLoadSchd")})
setGeneric(name = "SetPremLoadSchd<-", def = function(object, value) {standardGeneric("SetPremLoadSchd<-")})
setGeneric(name = "GetExpnsChrgSchd", def = function(object, ...) {standardGeneric("GetExpnsChrgSchd")})
setGeneric(name = "SetExpnsChrgSchd<-", def = function(object, value) {standardGeneric("SetExpnsChrgSchd<-")})
setGeneric(name = "GetExpnsChrgMode", def = function(object) {standardGeneric("GetExpnsChrgMode")})
setGeneric(name = "SetExpnsChrgMode<-", def = function(object, value) {standardGeneric("SetExpnsChrgMode<-")})
setGeneric(name = "GetExpnsChrgTiming", def = function(object) {standardGeneric("GetExpnsChrgTiming")})
setGeneric(name = "SetExpnsChrgTiming<-", def = function(object, value) {standardGeneric("SetExpnsChrgTiming<-")})
setGeneric(name = "GetMinIntrCredRate", def = function(object, ...) {standardGeneric("GetMinIntrCredRate")})
setGeneric(name = "SetMinIntrCredRate<-", def = function(object, value) {standardGeneric("SetMinIntrCredRate<-")})
setGeneric(name = "Contains", def = function(object, item) {standardGeneric("Contains")})



